osx_image: xcode7.3

sudo: required
dist: trusty

language: c

os:
  - osx

env:
  # https://github.com/electron-userland/electron-builder/issues/481
  - CSC_IDENTITY_AUTO_DISCOVERY=false

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- nvm install 6
- npm install -g node-gyp
- npm install
- npm prune
- cd src
- npm install
- cd ..


script:
- npm run typings:install
- ./node_modules/.bin/electron-rebuild -m src/node_modules
- npm run app:build
- cd app/node_modules/node-core-audio
- node-gyp rebuild --target=1.4.0 --arch=x64 --dist-url=https://atom.io/download/atom-shell
- cd ..
- cd ..
- cd ..
- npm run dist:osx
