osx_image: xcode7.3

sudo: required
dist: trusty

language: c

os:
  - osx

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- nvm install 6
- npm install
- npm prune
- cd src
- npm install
- cd ..


script:
- npm run typings:install
- ./node_modules/.bin/electron-rebuild
- npm run app:build
- npm run dist:osx
